### ISSUE TITLE
Declaration approve (Prod)

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#274]
===Доброго дня, перевірте будь-ласка в чому справа, помилка з підтвердженням декларації. Кажуть буквально вчора було ок====  
  
## Declaration approve request
- [ ] patch with verification code;

## Actual result (few responces)
- [ ] {"meta":{"url":"http://api-svc.il/api/declaration_requests/{GUID_HERE}/actions/approve","type":"object","request_id":"b2137137-98fb-4878-bb06-bc5252e51b01#23898","code":409},"error":{"type":"request_conflict","message":"Invalid transition"}}
- [ ] {"meta":{"url":"http://api-svc.il/api/declaration_requests/{GUID_HERE}/actions/approve","type":"object","request_id":"471ab9cb-074e-4110-a612-0f0c7c1f1ec6#3485","code":409},"error":{"type":"request_conflict","message":"Invalid transition"}}
- [ ] {"meta":{"url":"http://api-svc.il/api/declaration_requests/{GUID_HERE}/actions/approve","type":"object","request_id":"e5514e12-744f-40c6-bf75-84c7fa3f7df9#33535","code":409},"error":{"type":"request_conflict","message":"Invalid transition"}}

## Expected result
- [ ] approved response
